import { useCallback, useEffect, useMemo, useState } from 'react'
import { AlertTriangle, ChevronLeft, Info, Sparkles } from 'lucide-react'
import * as api from '@/lib/api.ts'
import { ActionButton, GlassPanel, IconButton } from '@/components/primitives'
import { Badge } from '@/components/ui/badge.tsx'
import type { Runtime } from '@/components/pm/shared.tsx'
import { ScrollArea } from '@/components/ui/scroll-area.tsx'
import { ClaudeAuthDock } from '@/components/auth/ClaudeAuthDock.tsx'
import { useSessionStore } from '@/stores/session-store.ts'
import { blockedProvidersFromSessions, effectiveProviderAvailability, effectiveWarnings as resolveEffectiveWarnings, getResolvedInteractiveCategory } from '@/lib/llm-policy.ts'
import { primeLLMSettingsPayloadCache } from '@/components/pm/shared.tsx'

type Props = {
  title?: string
  onBack?: () => void
  onClose?: () => void
  className?: string
}

type InteractiveRowDef = {
  key: string
  label: string
  description: string
  recommendation: string
}

type ServiceRowDef = {
  key: string
  label: string
  description: string
  recommendation: string
}

const AGENT_ROWS: InteractiveRowDef[] = [
  {
    key: 'concierge',
    label: 'Concierge',
    description: 'Greets the user, understands the request, and routes work into the right task or agent flow.',
    recommendation: 'Recommended default: use the same strong model you trust for planning and coordination.',
  },
  {
    key: 'task_agent',
    label: 'Task agent',
    description: 'The main project worker that reads tasks, edits files, and carries implementation work forward.',
    recommendation: 'Recommended default: use your strongest coding-capable model.',
  },
  {
    key: 'verifier',
    label: 'Verifier',
    description: 'Re-reads task outputs and checks whether the work really satisfies the acceptance criteria.',
    recommendation: 'Recommended default: keep this strong and careful rather than cheap.',
  },
  {
    key: 'shadow',
    label: 'Shadow',
    description: 'Background summarizer that watches a live session and keeps its session card up to date.',
    recommendation: 'Recommended default: use a cheaper fast model.',
  },
]

const WIDGET_ROWS: InteractiveRowDef[] = [
  {
    key: 'widget_builder',
    label: 'Widget builder',
    description: 'Agent sessions that scaffold and build widgets in the background.',
    recommendation: 'Recommended default: use the same model family as task-agent unless widgets need cheaper defaults.',
  },
  {
    key: 'paper_analysis',
    label: 'Paper analysis',
    description: 'Research KB analysis agents that read papers and write structured summaries or deeper analysis.',
    recommendation: 'Recommended default: use a stronger analysis-oriented model.',
  },
  {
    key: 'live_site',
    label: 'Live site',
    description: 'Agent sessions that build or revise live sites from a project brief.',
    recommendation: 'Recommended default: use the same strong build model as widget or task work.',
  },
]

const SERVICE_ROWS: ServiceRowDef[] = [
  {
    key: 'paper_filter',
    label: 'Paper filter & resolver',
    description: 'Quick one-shot LLM calls during paper discovery: filtering arxiv batches AND extracting title/authors/abstract/DOI from uploaded PDFs. Both share the same model.',
    recommendation: 'Recommended default: deepseek-v4-flash (cheap, fast, reliable JSON output via OpenAI-compat JSON mode).',
  },
  {
    key: 'paper_analysis',
    label: 'Paper analysis (preview)',
    description: 'One-shot summary generated by the "Preview Analysis" button in the paper-discovery widget. Smarter model recommended — this is the deep-reading task.',
    recommendation: 'Recommended default: deepseek-v4-pro (reasoning mode). Falls back to gemini-3-flash-preview if you want to compare.',
  },
  // image_generation intentionally hidden: the Gemini provider is currently
  // disabled in image_gen_mcp.py, so all generate/edit calls route through
  // Codex regardless of the model selection. The backend catalog and setting
  // are kept in place — re-add this row to expose user-configurable Gemini
  // model selection if the gemini provider is re-enabled.
]

const PROVIDER_LABELS: Record<string, string> = {
  claude: 'Claude',
  codex: 'Codex',
}

function providerToRuntime(provider: string): Runtime {
  return provider === 'codex' ? 'codex' : 'claude-code'
}

function firstModelForRuntime(payload: api.LLMSettingsPayload, runtime: Runtime): string {
  const resolved = payload.resolved_interactive_categories?.interactive_agent
  const source = resolved?.available_models || payload.selectable_models?.[runtime] || payload.available_models?.[runtime] || []
  return source.filter(option => option.id !== 'default')[0]?.id || 'default'
}

function SettingsModelSelect({
  value,
  options,
  onChange,
  className = '',
}: {
  value: string
  options: api.LLMModelOption[]
  onChange: (value: string) => void
  className?: string
}) {
  return (
    <select
      value={value}
      onChange={(event) => onChange(event.target.value)}
      className={[
        'h-10 w-full rounded-md border border-border bg-[var(--bg-panel)] px-3 type-label text-foreground outline-none transition-colors',
        'focus:border-[var(--color-accent)]',
        className,
      ].join(' ')}
    >
      {options.map(option => (
        <option key={option.id} value={option.id}>
          {option.label}
        </option>
      ))}
    </select>
  )
}

export function AISettingsPage({ title = 'AI Settings', onBack, onClose, className = '' }: Props) {
  const [payload, setPayload] = useState<api.LLMSettingsPayload | null>(null)
  const [draftSettings, setDraftSettings] = useState<api.LLMSettings | null>(null)
  const [saving, setSaving] = useState(false)
  const [status, setStatus] = useState('')
  const sessions = useSessionStore(s => s.sessions)
  const sessionStatuses = useSessionStore(s => s.sessionStatuses)

  const refresh = useCallback(async () => {
    try {
      const next = await api.fetchLLMSettings()
      primeLLMSettingsPayloadCache(next)
      setPayload(next)
      setDraftSettings(JSON.parse(JSON.stringify(next.settings || {})))
      setStatus('')
    } catch (err: any) {
      setStatus(err?.message || 'Failed to load AI settings.')
    }
  }, [])

  useEffect(() => {
    void refresh()
  }, [refresh])

  const updateSettings = (mutator: (draft: api.LLMSettings) => void) => {
    setDraftSettings(prev => {
      const next: api.LLMSettings = JSON.parse(JSON.stringify(prev || {}))
      mutator(next)
      return next
    })
  }

  const save = async () => {
    if (!draftSettings) return
    setSaving(true)
    try {
      const next = await api.saveLLMSettings(draftSettings)
      primeLLMSettingsPayloadCache(next)
      setPayload(next)
      setDraftSettings(JSON.parse(JSON.stringify(next.settings || {})))
      setStatus('Saved.')
    } catch (err: any) {
      setStatus(err?.message || 'Failed to save AI settings.')
    } finally {
      setSaving(false)
    }
  }

  const loggedInProviders = useMemo(
    () => {
      if (!payload) return []
      const blockedProviders = blockedProvidersFromSessions(sessions, sessionStatuses)
      return Object.entries(effectiveProviderAvailability(payload, blockedProviders))
        .filter(([, available]) => available)
        .map(([provider]) => provider)
    },
    [payload, sessionStatuses, sessions],
  )
  const providerAvailability = useMemo(
    () => {
      if (!payload) return { claude: false, codex: false }
      return effectiveProviderAvailability(payload, blockedProvidersFromSessions(sessions, sessionStatuses))
    },
    [payload, sessionStatuses, sessions],
  )
  const effectiveWarnings = useMemo(() => {
    if (!payload) return []
    return resolveEffectiveWarnings(payload, blockedProvidersFromSessions(sessions, sessionStatuses))
  }, [payload, sessionStatuses, sessions])
  const editableSettings = draftSettings || payload?.settings || {}
  const isDirty = useMemo(() => (
    !!payload && JSON.stringify(editableSettings) !== JSON.stringify(payload.settings || {})
  ), [editableSettings, payload])
  const handleProvidersChange = useCallback((providers: api.ProvidersMap) => {
    setPayload(prev => prev ? {
      ...prev,
      providers: Object.fromEntries(
        Object.entries(providers).map(([provider, status]) => [provider, !!status?.loggedIn]),
      ),
    } : prev)
    if (!isDirty) {
      void refresh()
    }
  }, [isDirty, refresh])

  if (!payload) {
    return (
      <div className="flex min-h-[240px] items-center justify-center text-sm text-muted-foreground">
        Loading AI settings…
      </div>
    )
  }

  const currentDefaultProvider = editableSettings.providers?.default_provider || ''

  const setDefaultProvider = (provider: string) => {
    updateSettings(draft => {
      draft.providers ||= {}
      draft.providers.default_provider = provider
    })
  }

  const setInteractiveProvider = (key: string, provider: string) => {
    updateSettings(draft => {
      draft.categories ||= {}
      draft.categories[key] ||= {}
      draft.categories[key]!.provider = provider
      draft.categories[key]!.runtime = providerToRuntime(provider)
      draft.categories[key]!.default_model_by_runtime ||= {}
      draft.categories[key]!.default_model_by_runtime![draft.categories[key]!.runtime!] ||= firstModelForRuntime(payload, draft.categories[key]!.runtime as Runtime)
    })
  }

  const setInteractiveModel = (key: string, provider: string, model: string) => {
    const runtime = providerToRuntime(provider)
    updateSettings(draft => {
      draft.categories ||= {}
      draft.categories[key] ||= {}
      draft.categories[key]!.provider = provider
      draft.categories[key]!.runtime = runtime
      draft.categories[key]!.default_model_by_runtime ||= {}
      draft.categories[key]!.default_model_by_runtime![runtime] = model
    })
  }

  const setServiceModel = (key: string, model: string) => {
    updateSettings(draft => {
      draft.services ||= {}
      draft.services[key] ||= {}
      draft.services[key]!.default_model = model
    })
  }

  const renderProviderButtons = (selectedProvider: string, onSelect: (provider: string) => void) => (
    <div className="flex flex-wrap gap-2">
      {(['claude', 'codex'] as const).map(provider => {
        const enabled = !!providerAvailability[provider]
        const active = selectedProvider === provider
        return (
          <ActionButton
            key={provider}
            type="button"
            disabled={!enabled}
            onClick={() => onSelect(provider)}
            variant={active ? 'toolbarPrimary' : 'toolbar'}
            size="toolbar"
            className="rounded-full px-3 disabled:cursor-not-allowed disabled:opacity-60"
          >
            {PROVIDER_LABELS[provider]}
          </ActionButton>
        )
      })}
    </div>
  )

  const renderInteractiveRow = (row: InteractiveRowDef) => {
    const state = getResolvedInteractiveCategory(
      payload,
      row.key,
      blockedProvidersFromSessions(sessions, sessionStatuses),
      editableSettings,
    )
    const selectableModels = state.availableModels
    const providerLoggedIn = state.providerAvailable
    const availableModelLabels = selectableModels.map(option => option.label).join(', ')
    return (
      <GlassPanel key={row.key} variant="card" className="rounded-2xl p-4">
        <div className="flex flex-col gap-3">
          <div className="flex flex-col gap-1">
            <div className="flex items-center gap-2">
              <h3 className="text-sm font-semibold text-foreground">{row.label}</h3>
              <Badge variant="outline" className="type-caption">Recommended</Badge>
            </div>
            <p className="type-label leading-5 text-muted-foreground">{row.description}</p>
            <p className="type-micro leading-5 text-[var(--color-accent)]">{row.recommendation}</p>
          </div>

          <div className="grid gap-3 md:grid-cols-[1.2fr_1fr]">
            <div className="flex flex-col gap-2">
              <div className="type-micro uppercase tracking-[0.18em] text-muted-foreground">Provider</div>
              {renderProviderButtons(state.provider, provider => setInteractiveProvider(row.key, provider))}
            </div>
            <div className="flex flex-col gap-2">
              <div className="type-micro uppercase tracking-[0.18em] text-muted-foreground">Model</div>
              <SettingsModelSelect
                value={state.model}
                options={selectableModels}
                onChange={value => setInteractiveModel(row.key, state.provider, value)}
                className="type-label"
              />
            </div>
          </div>

          <div className="flex flex-wrap items-center gap-2 type-micro text-muted-foreground">
            <span>Runtime: {state.runtime}</span>
            <span>Available models: {availableModelLabels || 'none'}</span>
            {!providerLoggedIn && (
              <span className="rounded-full border border-orange/30 bg-orange/10 px-2 py-0.5 text-orange">
                Provider not logged in
              </span>
            )}
          </div>
        </div>
      </GlassPanel>
    )
  }

  const renderServiceRow = (row: ServiceRowDef) => {
    const currentModel = editableSettings.services?.[row.key]?.default_model
      || payload.service_models?.[row.key]?.[0]?.id
      || ''
    return (
      <GlassPanel key={row.key} variant="card" className="rounded-2xl p-4">
        <div className="flex flex-col gap-3">
          <div className="flex flex-col gap-1">
            <div className="flex items-center gap-2">
              <h3 className="text-sm font-semibold text-foreground">{row.label}</h3>
              <Badge variant="outline" className="type-caption">Registry-backed</Badge>
            </div>
            <p className="type-label leading-5 text-muted-foreground">{row.description}</p>
            <p className="type-micro leading-5 text-[var(--color-accent)]">{row.recommendation}</p>
          </div>
          <div className="flex flex-col gap-2">
            <div className="type-micro uppercase tracking-[0.18em] text-muted-foreground">Model</div>
            <SettingsModelSelect
              value={currentModel}
              options={payload.service_models?.[row.key] || []}
              onChange={value => setServiceModel(row.key, value)}
              className="type-label"
            />
          </div>
        </div>
      </GlassPanel>
    )
  }

  return (
    <div className={`flex h-full min-h-0 flex-col bg-[linear-gradient(180deg,rgba(255,255,255,0.03),rgba(255,255,255,0.01))] ${className}`.trim()}>
      <div className="border-b border-[var(--color-border-glass)] px-5 py-4">
        <div className="flex items-start justify-between gap-4">
          <div className="flex items-start gap-3">
            {onBack && (
              <IconButton
                type="button"
                onClick={onBack}
                variant="appShell"
                size="sm"
                shape="round"
                className="mt-0.5 border-border"
                aria-label="Back"
              >
                <ChevronLeft size={14} />
              </IconButton>
            )}
            <div className="flex flex-col gap-1">
              <div className="flex items-center gap-2">
                <Sparkles size={14} className="text-[var(--color-accent)]" />
                <h1 className="text-lg font-semibold tracking-tight">{title}</h1>
              </div>
              <p className="max-w-3xl type-label leading-5 text-muted-foreground">
                Choose the default AI for the system, then set role-specific or tool-specific defaults only where they genuinely need to differ.
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            {onClose && (
              <ActionButton variant="toolbar" onClick={onClose}>Close</ActionButton>
            )}
            <ActionButton variant="toolbarPrimary" onClick={() => void save()} disabled={saving}>
              {saving ? 'Saving…' : 'Save changes'}
            </ActionButton>
          </div>
        </div>
      </div>

      <ScrollArea className="flex-1">
        <div className="mx-auto flex w-full max-w-6xl flex-col gap-5 px-5 py-5">
          <section className="flex flex-col gap-3">
            <div>
              <h2 className="text-sm font-semibold text-foreground">Provider Auth</h2>
              <p className="type-label text-muted-foreground">Login state is managed here. AI defaults below only use providers that are actually available.</p>
            </div>
            <GlassPanel variant="card" className="rounded-3xl p-4">
              <div className="settings-auth-embed">
                <ClaudeAuthDock
                  embedded
                  onProvidersChange={handleProvidersChange}
                />
              </div>
            </GlassPanel>
          </section>

          <GlassPanel variant="card" className="rounded-3xl p-5">
            <div className="grid gap-4 lg:grid-cols-[1.2fr_1fr]">
              <div className="flex flex-col gap-2">
                <div className="flex items-center gap-2">
                  <h2 className="text-sm font-semibold text-foreground">Default AI</h2>
                  <Badge variant="outline" className="type-caption">Required when both are connected</Badge>
                </div>
                <p className="type-label leading-5 text-muted-foreground">
                  This is the system-wide default provider used when a surface does not specify something more specific.
                </p>
                {renderProviderButtons(currentDefaultProvider, setDefaultProvider)}
                <div className="flex flex-wrap gap-2 type-micro text-muted-foreground">
                  <span>Connected: {loggedInProviders.length ? loggedInProviders.map(provider => PROVIDER_LABELS[provider] || provider).join(', ') : 'none'}</span>
                  {loggedInProviders.length === 1 && (
                    <span className="rounded-full border border-[var(--color-border-subtle)] px-2 py-0.5">
                      One provider is connected, so the backend can infer it automatically.
                    </span>
                  )}
                </div>
              </div>

              <div className="rounded-2xl border border-[var(--color-border-subtle)] bg-[rgba(255,255,255,0.025)] p-4">
                <div className="mb-2 flex items-center gap-2 text-sm font-semibold text-foreground">
                  <Info size={14} className="text-[var(--color-accent)]" />
                  What this changes
                </div>
                <ul className="flex list-none flex-col gap-2 type-label leading-5 text-muted-foreground">
                  <li>Concierge decides how new work is interpreted and routed.</li>
                  <li>Task agents handle planning, coding, and project execution.</li>
                  <li>Verifiers audit outcomes after work is complete.</li>
                  <li>Shadow runs in the background to summarize live sessions.</li>
                </ul>
              </div>
            </div>
          </GlassPanel>

          {effectiveWarnings.length > 0 && (
            <GlassPanel variant="card" className="rounded-2xl border-orange/30 bg-orange/10 p-4">
              <div className="mb-2 flex items-center gap-2 text-sm font-semibold text-orange">
                <AlertTriangle size={14} />
                Warnings
              </div>
              <div className="flex flex-col gap-1 type-label text-orange">
                {effectiveWarnings.map((warning, idx) => (
                  <div key={idx}>{warning}</div>
                ))}
              </div>
            </GlassPanel>
          )}

          <section className="flex flex-col gap-3">
            <div>
              <h2 className="text-sm font-semibold text-foreground">Advanced Agent Roles</h2>
              <p className="type-label text-muted-foreground">Only split these defaults when the role really needs behavior different from the global default.</p>
            </div>
            <div className="grid gap-4 xl:grid-cols-2">
              {AGENT_ROWS.map(renderInteractiveRow)}
            </div>
          </section>

          <section className="flex flex-col gap-3">
            <div>
              <h2 className="text-sm font-semibold text-foreground">Widgets</h2>
              <p className="type-label text-muted-foreground">Widget-related agent and Research KB defaults live together because they are product surfaces users can reason about.</p>
            </div>
            <div className="grid gap-4 xl:grid-cols-2">
              {renderInteractiveRow(WIDGET_ROWS[0])}
              {renderInteractiveRow(WIDGET_ROWS[2])}
            </div>
            <GlassPanel variant="card" className="rounded-3xl p-4">
              <div className="mb-3 flex items-center gap-2">
                <h3 className="text-sm font-semibold text-foreground">Research knowledge base</h3>
                <Badge variant="outline" className="type-caption">Grouped</Badge>
              </div>
              <div className="grid gap-4 xl:grid-cols-2">
                {renderInteractiveRow(WIDGET_ROWS[1])}
                {renderServiceRow(SERVICE_ROWS[0])}
                {renderServiceRow(SERVICE_ROWS[1])}
              </div>
            </GlassPanel>
          </section>

          <section className="flex flex-col gap-3">
            <div>
              <h2 className="text-sm font-semibold text-foreground">Other AI Tools</h2>
              <p className="type-label text-muted-foreground">Embeddings stay fixed. Voice settings stay separate. Only expose the tool defaults users are likely to care about.</p>
            </div>
            <div className="grid gap-4 xl:grid-cols-2">
              <GlassPanel variant="card" className="rounded-2xl p-4">
                <div className="flex h-full flex-col justify-between gap-3">
                  <div className="flex flex-col gap-1">
                    <div className="flex items-center gap-2">
                      <h3 className="text-sm font-semibold text-foreground">Image generation</h3>
                      <Badge variant="outline" className="type-caption">Codex only</Badge>
                    </div>
                    <p className="type-label leading-5 text-muted-foreground">
                      The Gemini image provider is currently disabled. All <code>generate_image</code> and <code>edit_image</code> calls route through Codex&rsquo;s built-in GPT image generation.
                    </p>
                  </div>
                  <div className="type-micro text-muted-foreground">
                    No model selection is exposed here while Gemini is disabled.
                  </div>
                </div>
              </GlassPanel>
              <GlassPanel variant="card" className="rounded-2xl p-4">
                <div className="flex h-full flex-col justify-between gap-3">
                  <div className="flex flex-col gap-1">
                    <h3 className="text-sm font-semibold text-foreground">Fixed services</h3>
                    <p className="type-label leading-5 text-muted-foreground">
                      Embeddings stay on the current local embedding service. Deepgram voice remains outside this page.
                    </p>
                  </div>
                  <div className="type-micro text-muted-foreground">
                    These are intentionally not user-configurable here.
                  </div>
                </div>
              </GlassPanel>
            </div>
          </section>

          <div className="flex items-center justify-between border-t border-[var(--color-border-subtle)] pt-4">
            <div className="type-micro text-muted-foreground">{status || 'Unavailable providers are shown but cannot be selected.'}</div>
            <ActionButton variant="toolbarPrimary" onClick={() => void save()} disabled={saving}>
              {saving ? 'Saving…' : 'Save changes'}
            </ActionButton>
          </div>
        </div>
      </ScrollArea>
    </div>
  )
}
